### ISSUE TITLE
Samples not generating

### ISSUE THREAD

**Issue by faucetlol** [Earlopain/reverser#100]
![image](https://github.com/Earlopain/reverser/assets/102884856/dafae914-4323-4dba-b2f7-b3d07fb733b3)

Not sure what's happening here.

**Comment by Earlopain** [comment]
Probably because of the rails upgrade, there must have been a change regarding this. I'll check it out. https://github.com/Earlopain/reverser/blob/42aa4713b06fb88b7ae624cdbcf0ce53196b3466/app/models/submission_file.rb#L122-L126

**Comment by Earlopain** [comment]
New config `run_after_transaction_callbacks_in_order_defined` is true by default which causes an internal `after_commit` to run before this and deletes the attachment changes.

**Comment by Earlopain** [comment]
Run this to fix stuff up:

```rb
last_good_id = 123
SubmissionFile.where("id >= ?", last_good_id).find_each { |sm| SubmissionFileUpdateJob.perform_later(sm) }
```

**Comment by faucetlol** [comment]
That moment when I'm so tired I forget to replace `123` with the actual last good ID and end up queuing 23,712 jobs before I realise what I did wrong

Either way, thanks for the prompt fix as usual!

**Comment by Earlopain** [comment]
I'll keep that in mind when posting fixer stuff in the future, lmao
