### ISSUE TITLE
Newgrounds now supports multiple images per submission 

### ISSUE THREAD

**Issue by faucetlol** [Earlopain/reverser#102]
The scraper currently only grabs the first image.

Example submission:
https://www.newgrounds.com/art/view/kooriki/early-bird-gets-the-wyrm

**Comment by faucetlol** [comment]
I was about to try and deal with this but there's more than I'm wanting to deal with right now. I can probably take a look within the next few days.

There's also a comic layout as well as multi-image submissions:
https://www.newgrounds.com/art/view/ethandoesathing/legend-of-arcana-ch-1-pages

Some images are now also served with webp samples, haven't found any live examples of this yet though.

More details at: https://www.newgrounds.com/bbs/topic/1528343

**Comment by Earlopain** [comment]
I can let you do this when you got time if you want

**Comment by faucetlol** [comment]
> I can let you do this when you got time if you want

Well I'm not particularly attached, I just feel bad dropping issues here and not dealing with many of them myself. The webp and inline/strip layouts look easy enough to deal with but that comic layout seems like it's going to be hell to deal with since it's an HTML scraper.

**Comment by Earlopain** [comment]
That should do it. I'm don't know if you can edit multi image submissions to add new images but I do know is that if that is possible they won't be added in future scrapes.

**Comment by faucetlol** [comment]
Looks great, thanks! That comic solution actually looks surprisingly easy.
