### ISSUE TITLE
FA search sometimes takes a very long time to index posts

### ISSUE THREAD

**Issue by faucetlol** [Earlopain/reverser#113]
I've encountered this a lot lately where FA takes _forever_ to actually index posts in their searches. It's always taken a few minutes at minimum, which has resulted in posts missing being scraped in the past, but I'm observing posts that are being missed being scraped because they don't appear in the search hours later. The issue usually does seem to resolve itself on FA's end, but does require manual intervention in Reverser to roll back all the `last_scraped_at` dates for FurAffinity URLs. Manual intervention isn't too hard, but it can be difficult to notice that the scraper has even missed the content to begin with.

These two posts, at minimum, had existed for hours on FA at the time I ran the scraper and don't appear in FA search results. I've also manually searched FA and confirmed they do not appear in search results.
* https://www.furaffinity.net/view/55216454/ (8 hours ago)
* https://www.furaffinity.net/view/55216974/ (7 hours ago)

I've avoided making an issue for a while not because I'm really not sure if there's anything better Reverser could be doing here, as it entirely seems to be FA's problem. Even if there's nothing that can be done, I guess it at least serves as some sort of warning for users.

I'm just spitballing some potential solutions here, but I think they're all disadvantageous or hacky.
* Using the gallery endpoint should avoid this, but the search endpoint comes with so many benefits like including gallery and scraps in one search or still giving results for disabled accounts.
* Using the most recent submission as the cutoff date rather than the last scrape - might work well for FurAffinity, but I'm not sure how well that would work with other scrapers considering some sources don't even have hour/minute accuracy.
* Since the most recent file will still get scraped, even if it's older than the `last_scraped_at` date, it could possibly be detected that the newly scraped file was actually posted prior to the last scraper running and roll back the `last_scraped_at` date by a few days to ensure any other content is scraped. I don't think this solution would work if any new posts were posted to the gallery since the problem occurred.

**Comment by faucetlol** [comment]
Also a somewhat related feature request: would it be possible for the "Enqueue Everything" on `/artists` to only enqueue the current search results (or everything if the page currently isn't filtered) in a similar vein to "Update IQDB for matching"? It would be very handy for when I want to specifically enqueue URLs from a certain site.

**Comment by Earlopain** [comment]
> Using the most recent submission as the cutoff date rather than the last scrape - might work well for FurAffinity, but I'm not sure how well that would work with other scrapers considering some sources don't even have hour/minute accuracy.

This seems like my prefered approach for this. Not sure how well this would play with other scrapers so I'll just make this an option for specific scrapers when needed like in this case.

> Also a somewhat related feature request: would it be possible for the "Enqueue Everything" on /artists to only enqueue the current search results (or everything if the page currently isn't filtered) in a similar vein to "Update IQDB for matching"? It would be very handy for when I want to specifically enqueue URLs from a certain site.

I don't think I understand what you're asking for. Could you make a separate issue explaining what you're wanting to do and why this doesn't work?

**Comment by Earlopain** [comment]
This should do it I think. Let me know how this goes

**Comment by faucetlol** [comment]
Looks good to me, if it works properly I probably won't notice it working - so assume that no news is good news.

Only (unavoidable?) downside I'm seeing is the last scraped column isn't really that useful anymore
![image](https://github.com/Earlopain/reverser/assets/102884856/c6192619-5563-40ba-975b-3068e4e70424)

**Comment by Earlopain** [comment]
Fixed with https://github.com/Earlopain/reverser/commit/4f7640bc41fbd54b1a242bdd76fb05d9451aa8c6

**Comment by faucetlol** [comment]
Great, thank you!
