### ISSUE TITLE
Add User-Agent header to requests

### ISSUE THREAD

**Issue by DonovanDMC** [Earlopain/reverser#117]
After messing around for a while trying to figure out why the tumblr scraper refused to work for me (it threw back a generic 403 instead of any specific error), I finally decided to try adding a `User-Agent` header to the request and it started working just fine. They seem to be blocking the default `httpx.rb/1.1.5` value the library that's used is sending. As far as I can tell, this has been an issue since the switch was made in 4575f8251eaa4d63211f2af5498b6ea4b2edb574

You might also be wary of it possibly ignoring the params, since they aren't showing in the url
![image](https://github.com/Earlopain/reverser/assets/17226394/5ad6caf9-c536-4341-a133-91b4edea5b99)

**Comment by Earlopain** [comment]
They probably block the python library of the same name. I'll add a header like for reddit, and should do that for all other sites that provide an api.

Params aren't shown because its `POST` and they aren't part of the url (no query params). They should show in details however.

**Comment by DonovanDMC** [comment]
> They probably block the python library of the same name. I'll add a header like for reddit, and should do that for all other sites that provide an api.
> 
> Params aren't shown because its `POST` and they aren't part of the url (no query params). They should show in details however.

It isn't a post request, it's a GET.

**Comment by Earlopain** [comment]
It was just a display error.

Added a useragent to tumblr, that should do it. Though I probably need to look at others and see if they need something similar
