### ISSUE TITLE
It takes forever to connect to Selenium

### ISSUE THREAD

**Issue by faucetlol** [Earlopain/reverser#120]
Whenever trying to connect to Selenium I usually get stuck on the "Connecting..." screen for quite a few minutes before it finally connects. It's been happening to me for a while now, so I don't remember at which point it started, but it's infrequent enough that it never bothers me too much. 

The console output is just this over and over and over:

```
selenium-1  | 09:30:47.812 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "f088b72f4a2d57c55826933218555b74","eventTime": 1714987847811851210,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f7e8d36ecf0bc377a3bc69f64c103d8b7\u002fcookie\u002fa","http.user_agent": "selenium\u002f4.17.0 (ruby linux)"}}
selenium-1  |
selenium-1  | 09:30:48.023 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "7489d306fafef5bdc6e11fe6773c7c3f","eventTime": 1714987848022758926,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f7e8d36ecf0bc377a3bc69f64c103d8b7\u002fcookie\u002fa","http.user_agent": "selenium\u002f4.17.0 (ruby linux)"}}
selenium-1  |
selenium-1  | 09:30:48.233 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "723340549465b5567cc0abd267c07349","eventTime": 1714987848232362788,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f7e8d36ecf0bc377a3bc69f64c103d8b7\u002fcookie\u002fa","http.user_agent": "selenium\u002f4.17.0 (ruby linux)"}}
selenium-1  |
selenium-1  | 09:30:48.443 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "1676debb22b40aa5876cccb0c1d74cc0","eventTime": 1714987848442695225,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.remote.http.Route$PredicatedRoute","http.host": "selenium:4444","http.method": "GET","http.scheme": "HTTP","http.status_code": 404,"http.target": "\u002fsession\u002f7e8d36ecf0bc377a3bc69f64c103d8b7\u002fcookie\u002fa","http.user_agent": "selenium\u002f4.17.0 (ruby linux)"}}
```

**Comment by Earlopain** [comment]
Is this about the NoVNC web interface (http://localhost:7900 or whatever)? If so, yes, that is an issue I had in the past as well. I reported that upstream and eventually found the cause and implemented a fix https://github.com/SeleniumHQ/docker-selenium/issues/2045

Unfortunatly this regressed and I updated to a version of selenium that was broken again without noticing, though the version of selenium currently used in the dockerfile should work normally. Are you on HEAD?

**Comment by faucetlol** [comment]
>  Are you on HEAD?

Oops, I just commit the cardinal sin of making an issue without actually being on the latest version.

 I was still on a9a1b5a77ee155d50239905db71e8ca3b0dea4dc and hadn't really bothered checking for new commits since this has been a problem for quite a few months now. 

Since I have my FA cache time set to quite a few months (and that's just about the only reason I ever need to use the NoVNC web interface) I probably didn't notice it start working and then break again.

**Comment by Earlopain** [comment]
Impressive that you tolerated it this long. If you said something earlier I would have rolled back to some older selenium version. I didn't think someone else runs into this apart from me.

**Comment by faucetlol** [comment]
Likewise I just assumed it was only me, I'm usually not using Reverser from the same machine that it's running from so I thought it might've been something to do with that. With my longer cache time I've probably only had to deal with it 3-4 times since your issue in December, so it really wasn't too big of a deal for me - it normally would've connected in the time it took me to tag a post.
