### ISSUE TITLE
FurAffinity invalid date

### ISSUE THREAD

**Issue by DontTalkToMeThx** [Earlopain/reverser#121]
Was getting `Error: Date::Error: invalid date` when trying to scrape fur affinity.

This happens because the content of the date is not the actual date, but an "ago" syntax.

Changing `/app/logical/scraper/furaffinity.rb` line 23 from `time_string = html.css(".submission-id-container .popup_date").first.content.strip` to `time_string = html.css(".submission-id-container .popup_date").first.attribute("title")` fixed the problem.

Now I would PR this as a fix, but I really don't see the point in forking for one line.

**Comment by faucetlol** [comment]
The fix wouldn't work when the account settings are set to "Full Date Format" because the title and content are flipped, then the ago syntax would be the title.

![image](https://github.com/Earlopain/reverser/assets/102884856/da3c0ffe-8a32-42e8-b8e7-db22131f8e32)

**Comment by faucetlol** [comment]
Damn, you beat me to it

**Comment by Earlopain** [comment]
> Damn, you beat me to it

Oops, sorry. Just write as much in the future so I don't accidentally snipe. I don't mind that

-------

There used to be some text somewhere telling you to modify this setting but I don't think that exists here anymore. It's no bother to just check both versions instead.

**Comment by faucetlol** [comment]
> Oops, sorry. Just write as much in the future so I don't accidentally snipe. I don't mind that

It's no problem - just thought it was funny we were both doing it at the same time. 

> There used to be some text somewhere telling you to modify this setting but I don't think that exists here anymore. It's no bother to just check both versions instead.

It's still a comment in the yml config, though that's not much help if you're using the in-app configuration. https://github.com/Earlopain/reverser/blob/c5347bb09a767db8efb42b3dac73954aac602975/config/reverser.yml#L44
