### ISSUE TITLE
Hide submissions on artist pages too

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#54]
Being able to hide posts on the submission files page is very useful, would be great to be able to do it on the artist pages too. Or perhaps be able to filter the submission files by artist? Either solution gives the same result I'm looking for.

**Comment by Earlopain** [comment]
You mean hiding hidden submission files when on /artists/123? I haven't used that since then, was mostly spending my time on the submission files index. I agree that also hiding them there makes sense.

**Comment by faucetlol2** [comment]
Yeah those are what I mean, I've been using the artist pages a lot because certain people are the biggest offenders for having more selfies and photos of their cat than actual art and it makes it a lot easier to clean up if I just filter everything to those people.

**Comment by Earlopain** [comment]
Neat, I haven't though about being able to use it like that.

I also added artist url searching to the hidden submission files page. I'm not sure if that is what you mentioned as an alternative solution, but nice to have either way.
