### ISSUE TITLE
Can't scrape usernames containing ~ on Fur Affinity

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#56]
I've been trying to scrape the user [\~Bulochka\~](https://www.furaffinity.net/user/~bulochka~/) on Fur Affinity, and the scraping fails because of the way Fur Affinity handles ~ in the searches. It looks like it requires stripping both of the tilde symbols to be able to get a successful search with `@lower bulochka`, which is different to - working as long as it's not at the start of the username. This also introduces a small concern of scraping stuff from the wrong user since there's a user named [bulochka](https://www.furaffinity.net/user/bulochka), though they've luckily not uploaded anything.

Simply just stripping them out doesn't seem to be a perfect solution because searching `@lower bloominglynx` doesn't return any results at all for [Blooming~Lynx](https://www.furaffinity.net/user/blooming~lynx)

_Why did FA even think it was a good idea to allow search operators inside usernames??_

**Comment by faucetlol2** [comment]
`@lower blooming-lynx` returns results - perhaps the best method is to replace **~** with **-** and then the existing logic that's already there should handle it just fine.

**Comment by Earlopain** [comment]
> `@lower blooming-lynx` returns results - perhaps the best method is to replace **~** with **-** and then the existing logic that's already there should handle it just fine.

I'll try that out, sounds good.



I'm already validating the name below submissions against what was searched, since the search seems to be wildcarding. Searching for `scale` also returns results for `blue-scale`. I documented my adventures with the search system in the scraper if you want to take a look.

**Comment by faucetlol2** [comment]
I tried tweaking it myself to add `gsub("~", "-")` before the `delete_prefix` and that seems to work perfectly, the scraper runs just fine.
