### ISSUE TITLE
[Feature] "Select All"/checkboxes on submission files

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#59]
Sometimes there's pages full of content I don't want to upload, and having to click the H 25 times per page is kinda exhausting when there's a few hundred pages I want to do it with. Having a "Select All" option and checkboxes like e621's [post changes page](https://e621.net/post_versions) would be pretty nice.

![image](https://user-images.githubusercontent.com/102884856/195606307-15090da0-aa89-4958-a7e8-11e384c3aa95.png)

I'd understand if this one was too much effort though, Reverser does seem pretty minimal in JS usage at the moment.

**Comment by Earlopain** [comment]
I'm not hiding much myself, but I can see how it can get annoying, especially since clicking on a single letter isn't all that easy. Same for the backlog.

I will add this sometime
