### ISSUE TITLE
Add manual IQDB queries to the front of the queue

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#64]
Would it be possible to add manual IQDB queries to the front of the queue when hitting the UREV button? Sometimes I have a few thousand things in the queue and it's not very fun waiting for them to all complete before I can update a single image.

**Comment by Earlopain** [comment]
That's a reasonable request, and I had the same though previously as well. From what I can remember it was not trivial when using sidekiq, but goodjob seems to suport a `priority` keyword when adding to queues (or it's just a ActiveJob thing, not sure). Either way, it should be trivial to add.

**Comment by Earlopain** [comment]
Job adapters can choose to support the priority parameter on a per queue or job basis, or not at all. Sidekiq does per queue, GoodJob per job which helps immensely for this. Learned something new about ActiveJob backends, I though it's a universal interface, but job adapters can choose to implement what they want.

This feels incredibly good to use, thanks for requesting!
