### ISSUE TITLE
PG relations not being created?

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#69]
After making a fresh install and trying to view the Artists page.

```
ActiveRecord::StatementInvalid exception raised
PG::UndefinedTable: ERROR: relation "artists" does not exist LINE 9: WHERE a.attrelid = '"artists"'::regclass ^

Request
{
  "params": {
    "controller": "artists",
    "action": "index"
  },
  "referrer": null,
  "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
}

Stacktrace
app/models/artist.rb:72:in `search'
app/controllers/artists_controller.rb:24:in `index'
app/controllers/application_controller.rb:26:in `with_time_zone'
```

Similar error on other pages that require the `submission_files` relation too.

**Comment by Earlopain** [comment]
I might have messed something up when removing the old migrations, seemed to work fine for me though. Did you follow the new instructions in the readme? If so, reverting to 289339d5e930aede8390d5f7fd35fa6de4b7982a and doing a fresh install there should allow you to progress for the moment.

**Comment by faucetlol2** [comment]
...I didn't notice the readme had changed. That's embarrassing.

Works fine now.
