### ISSUE TITLE
`api_identifier` column never gets filled if URL was created before scraper was enabled

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#70]
The `api_identifier` column in the database never gets filled for URLs that don't have a scraper enabled. This makes sense at the point that the URL is added, but it remains null even after the scraper gets enabled meaning that any scrapers depending upon `api_identifier` just aren't going to work with URLs that were added prior to it being enabled. 

Since API identifier should never be null for a URL with an enabled scraper, it should be pretty trivial to do a null check and call the `fetch_api_identifier` method if necessary, right?

**Comment by Earlopain** [comment]
There's a fixer script you can run after adding scraper capabilities to a site. Just pass the site enum when calling it and you should be good

**Comment by faucetlol2** [comment]
Oh.. sure wish I looked for that before manually grabbing the API identifier for all those URLs 😐
