### ISSUE TITLE
`Identifier https: is not valid for Manual` for Twitter links

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#75]
Trying to add a Twitter URL to an artist results in the error: `Identifier https: is not valid for Manual`

Other websites seem to work just fine.

![IMG_20230109_070107_084](https://user-images.githubusercontent.com/102884856/211255384-baeffe75-fd4e-4303-8fd9-e2f55a857c10.jpg)

**Comment by Earlopain** [comment]
I think every definition after the manual failed to match because its regex was too eager. Should be good now
