### ISSUE TITLE
E6IqdbQueryJob frequently failing

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#76]
E6IqdbQueryJob seems to be failing a good portion of the time. Good Job gives the following error, and seems to be the same on all failed jobs that I checked.

```
Error: NameError: undefined local variable or method `post' for #<SubmissionFile id: 39620, artist_submission_id: 36698, created_at: "2023-01-09 07:47:28.817286000 +0100", updated_at: "2023-01-09 07:47:28.995063000 +0100", direct_url: "https://d.furaffinity.net/art/millkydad/1626825579...", created_at_on_site: "2021-07-21 02:30:00.000000000 +0200", file_identifier: "", width: 900, height: 900, size: 883058, content_type: "image/png", added_to_backlog_at: nil, iqdb_hash: "?\xE5\xE4\xAB\x0F\xC7R\x95?\xADf\xEA\xAA\xF5\x98\x95?\x91\x90 \xBF\xEC\xE8\xC2\xFA\x00\xFA\x7F\xFB\xF7\xFCs\xFC|\xFC}\xFC\xF9\xFDr\xFD~\xFD\xFF\xFEy\xFE\xF2\xFE\xFE...", hidden_from_search_at: nil>
```

If you need any further info than that, just let me know

**Comment by Earlopain** [comment]
Yeah, I see the issue. https://github.com/Earlopain/reverser/blob/6e120d0a9ff4fa6992a193a3abdba5acff932fa8/app/models/submission_file.rb#L164
I wonder why I didn't run into this myself. I'll fix it once I'm home and try to add some test for this.
