### ISSUE TITLE
`JSON::GeneratorError: source sequence is illegal/malformed utf-8` with Fur Affinity scraper

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#79]
When trying to scrape https://www.furaffinity.net/user/golublol/ the scraper fails with the error `JSON::GeneratorError: source sequence is illegal/malformed utf-8`

Not really sure how to track down the exact cause of it, but https://www.furaffinity.net/view/50575910 is the last URL on the scraper logs before it retries.

Also getting the same problem with https://www.furaffinity.net/user/cloudsen, but that URL takes about 5 minutes before failing rather than pretty much instant.

edit: + https://www.furaffinity.net/user/v3nusbby

**Comment by Earlopain** [comment]
![image](https://user-images.githubusercontent.com/14981592/212143606-c689df44-3514-476f-b962-32ae492f9e37.png)

![image](https://user-images.githubusercontent.com/14981592/212143519-80ea9ef3-2465-443f-8908-e95f566bce2c.png)

Thanks FA, I appreciate it
