### ISSUE TITLE
Update IQDB for matching with backlog

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#81]
Just learned the hard way that clicking "Update IQDB for matching" on the backlog page updates absolutely everything. It would be nice if it did it for only the posts in the backlog as expected, though I'm pretty sure I won't be making this mistake again for quite a while.

**Comment by Earlopain** [comment]
It's not expected behaviour, that's for sure. It will probably take quite a while for all the jobs to clear. Luckily goodjob stores its jobs in the normal postgres db, so it should be quite simple to just clear them.

Try something like this (untested):
```rb
# Confirm that the count looks about right
ActiveRecord::Base.connection.execute("select COUNT(*) from good_jobs where queue_name = 'e6_iqdb' and finished_at is null").first
# Throw em away
ActiveRecord::Base.connection.execute("delete from good_jobs where queue_name = 'e6_iqdb' and finished_at is null")
```

**Comment by faucetlol2** [comment]
I did try that last night, but afterwards realised that the entry in `e6_posts` gets destroyed before the E6IqdbQueryJob gets queued, meaning that everything was showing as not uploaded. Didn't have a backup of it prior to doing this, so I just decided to wait it out overnight, only a few thousand left now.

**Comment by Earlopain** [comment]
Oh, right. They do get deleted so you don't look at stale data after stuff gets enqueued

**Comment by faucetlol2** [comment]
Another somewhat related request to this. The IQDB jobs spawned by UpdateMatchingE6PostsJob have the same priority (10) as the jobs created by clicking UREV on an individual submission file, if possible it would be ideal for the manual jobs to have a higher priority than these again.

**Comment by Earlopain** [comment]
The priority should work better now. Single UREV _always_ comes first, then those through manual actions like clicking on UI links, and the ones added through scraping come in last.

**Comment by faucetlol2** [comment]
Perfect 👌
