### ISSUE TITLE
`Validation failed: Url identifier has already been taken` when adding archive

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#89]
After uploading an archive for one artist, it seems to be impossible to add any more because of conflicting URL identifiers.

___

Validation failed: Url identifier has already been taken
### Request
```
 {
  "params": {
    "import": {
      "file": "#<ActionDispatch::Http::UploadedFile:0x00007feab5de4f20>",
      "artist_id": "114",
      "source_url": "https://drive.google.com/drive/folders/1BIyQyBiaI5j2HK12aqbgN3i2vzp9pJNV"
    },
    "commit": "Upload and Import",
    "controller": "archive_imports",
    "action": "create"
  },
  "referrer": "http://localhost:9000/archive_imports/new",
  "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
} 
```

### Stacktrace
```
app/logical/archives/manual.rb:9:in `import_submission_files'
app/logical/archives/base.rb:16:in `import'
app/controllers/archive_imports_controller.rb:9:in `create'
app/controllers/application_controller.rb:25:in `with_time_zone'
```

**Comment by faucetlol2** [comment]
Currently mitigating the problem for myself by changing this line

https://github.com/Earlopain/reverser/blob/9247bd1a954399ca311252a3b1c92827fe233253/app/logical/archives/manual.rb#L10

`url.url_identifier = "manual-#{artist_id}"`

**Comment by Earlopain** [comment]
I only made this for one of those free PWYW bundles on gumroad and didn't test much more. Sorry about that
