### ISSUE TITLE
Tumblr url issues

### ISSUE THREAD

**Issue by DonovanDMC** [Earlopain/reverser#91]
`https://www.tumblr.com/catsudon` assumes www is the name.
`https://tumblr.com/catsudon` gives back a `no implicit conversion of Symbol into Integer` error.
> app/models/artist.rb:21:in \`block in add_artist_url'
app/models/artist.rb:15:in \`add_artist_url'
app/controllers/artists_controller.rb:79:in \`block in add_new_artist_urls_and_save'
app/controllers/artists_controller.rb:78:in \`map'
app/controllers/artists_controller.rb:78:in \`add_new_artist_urls_and_save'
app/controllers/artists_controller.rb:42:in \`update'
app/controllers/application_controller.rb:25:in \`with_time_zone'

`https://catsudon.tumblr.com` on the other hand works fine.

**Comment by faucetlol** [comment]
`no implicit conversion of Symbol into Integer` isn't much of a user-friendly error, but it happens when the input URL doesn't match any of the gallery templates.

Nice to see you here too :p

**Comment by Earlopain** [comment]
Fixed this erroring as well

**Comment by DonovanDMC** [comment]
> `no implicit conversion of Symbol into Integer` isn't much of a user-friendly error, but it happens when the input URL doesn't match any of the gallery templates.
> 
> Nice to see you here too :p

Ah, that is.. not user friendly in the slightest, neat
