### ISSUE TITLE
Stats page not working

### ISSUE THREAD

**Issue by DonovanDMC** [Earlopain/reverser#94]
No matter how many jobs I have running, the stats page shows zero across the board. It worked before the recent goodjob migration.
![image](https://github.com/Earlopain/reverser/assets/17226394/174e2ff3-fb65-4976-88f9-a07b3a4a3b09)

**Comment by Earlopain** [comment]
It was https://github.com/Earlopain/reverser/commit/ed4b7c7fbce7aabc23ef9c34e864fd3320716291

**Comment by DonovanDMC** [comment]
Brilliant
I knew it was somewhere around there
