### ISSUE TITLE
Proper logo

### ISSUE THREAD

**Issue by Earlopain** [Earlopain/reverser#99]
@faucetlol @donovandmc

I beg you, help me create a nice logo for this. Having nothing in the urlbar is annoying. Here's something I generated with StableDiffusion, I would say it looks okayish. Not great, not terrible. Fuck if I know what I'm looking at when seeing it rendered as a favicon though.

![logo](https://github.com/Earlopain/reverser/assets/14981592/23eb2943-8388-42f4-aa2b-e86c5c08e158)

I'm not picky, if you come up with something that looks neat and is tangentially related to the project I'd love to see that.

**Comment by faucetlol** [comment]
I'm no graphic designer so I don't think I can help you there, this sure beats having ![image](https://github.com/Earlopain/reverser/assets/102884856/76d25cbb-cc18-4a98-9618-bc6e09838a39) in my URL bar either way.

I'm not seeing it in the navbar though, is there some command I need to run to rebuild the scss? I already tried `docker compose run reverser pnpm run build:css` and that didn't seem to help.

**Comment by DonovanDMC** [comment]
I'm not great at icons either, I just crop images of my sona and call it a day 🤷

That icon looks good enough to me, though. Definitely better than nothing

**Comment by Earlopain** [comment]
Well, I guess I'll close this then. Just something to keep in mind if creativity strikes
